kind: Service
apiVersion: v1
metadata:
  name: freelancing-svc
  labels:
    app: freelancing-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32500
  selector:
    app: freelancing-app
  type: NodePort
